/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vidavid' at '7/31/16 10:43 AM' with Gradle 2.13
 *
 * @author vidavid, @date 7/31/16 10:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
